""" The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?"""

import math
import timeit

def divs(n):    
    sq = int(math.sqrt(n))
    r = range(2,sq+1)   
    y = [n / i for i in r if n%i==0]
    return len(y)*2 + 2

def euler12(x):
    t,n=0,1
    while(t:=t+n):
        n+=1
        if t<x: continue
        if divs(t) > x: return t      

print(euler12(5))
print(euler12(500))

t = timeit.Timer( lambda: euler12(500) )
print ( "Euler 12, %.5f ms" % (t.timeit(1) * 1000)  )
