# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
from benchmark import timed

def P(n):
    return n*(3*n-1)//2

# Let's start with a limit of 5k
N=5000
pens = [P(n) for n in range(1,N+1)]
cache = set(pens)

# The difference Pn+1-Pn increases with n, so just need to find the first match
@timed
def find():
    for j in range(1,N-1):
        for k in range(j+1,N-2):
            Pj, Pk = pens[j], pens[k]
            D = Pk-Pj
            if D in cache and Pj+Pk in cache: 
                return D

print( find() )